on:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
          
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --config .pre-commit-config.yaml --all-files
